version: '3.1'

services:
    web:
        container_name: web
        build: .
        #command: >
        #    sh start.sh
        #volumes:
        #    - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - db_nw
            - web_nw
    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 8080:80
        networks:
            - web_nw
        depends_on:
            - web
    db:
        container_name: db
        image: postgres:latest
        environment:
            #- POSTGRES_DB="${POSTGRES_DB}"
            #- POSTGRES_USER="${POSTGRES_USER}"
            #- POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
            POSTGRES_USER: ${POSTGRES_USER} # The PostgreSQL user (useful to connect to the database)
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # The PostgreSQL password (useful to connect to the database)
            POSTGRES_DB: ${POSTGRES_DB} # The PostgreSQL default database (automatically created at first launch)
            PGDATA: /var/lib/postgresql/data
            #POSTGRES_DB: postgres
            #POSTGRES_USER: admin
            #POSTGRES_PASSWORD: secret
            #PGDATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        networks:
            - db_nw
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 81
        ports:
            - "8081:81"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
        networks:
            - db_nw
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
    dbdata:
    pgadmin-data: